### ISSUE TITLE
User can see a list of food types. 

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#1]
## 💰 Motivation

A user should be able to see the different types of food there are to eat.

## 📐 Plan

Create a page that allows the user to see the different food types available to search by.

## 🖼️ Wireframe

<img width="223" alt="Screen Shot 2021-04-05 at 3 42 40 PM" src="https://user-images.githubusercontent.com/76749207/113635484-956f7c80-9625-11eb-83c5-9e907ea6782a.png">

<img width="283" alt="Screen Shot 2021-04-05 at 5 28 06 PM" src="https://user-images.githubusercontent.com/76749207/113642332-6dd3e080-9634-11eb-8f09-602b4fac6a06.png">

## ✅ Task List

- [x] Create component directory and header.jsx in pages folder
- [x] Create header react element 
- [x] Add app name to header and app drawer icon
- [x] Import to Header to Home
- [x] Style to figma
- [x] Create search.jsx in pages
  - [x] Create and export Search component
  - [x] Create render method to return react element
  - [x] react element calls SearchForm component
- [x] Create search-form.jsx in components
  - [x] Import appropriate packages/components
  - [x] Create and export class component SearchForm
  - [x] Create render method to return react element 
    - [x] Create div for search page 
    - [x] Create form element with input element and buttons
      - [x] Add place holder for input element saying "location"
      - [x] Add button elements containing the food types
      - [x] Add submit button for search functionality
    - [x] Import to Search component
- [x] Import to app.jsx
  - [x] Style according to figma
  - [x] Test on private browser
  - [x] Fix all errors
