### ISSUE TITLE
User can remove restaurant from randomizer list 

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#10]
## 💰 Motivation

A user should be able to remove a restaurant from the list for the app to randomly select where to eat.

## 📐 Plan

Add functionality to check button to remove a specific restaurant from the randomizer list.

## 🖼️ Wireframe

<img width="506" alt="Screen Shot 2021-04-05 at 4 47 59 PM" src="https://user-images.githubusercontent.com/76749207/113639746-b25c7d80-962e-11eb-9469-e53b519deae4.png">

<img width="560" alt="Screen Shot 2021-04-05 at 5 19 20 PM" src="https://user-images.githubusercontent.com/76749207/113641758-1f721200-9633-11eb-8926-1d83e68d3b92.png">

## ✅ Task List

- [x] In handleClick method of CheckIcon, create reqDelete object with method, headers, and body property
  - [x] method: delete
  - [x] header: 'Content-Type': 'application/json'
  - [x] body: this.state.restaurant
- [x] Create fetch request in else statement with reqDelete argument
- [x] In index.js, create delete request
  - [x] Destructure alias from req.body
  - [x] Throw error if alias doesn't exist
  - [x] Create const sql variable with sql string delete from "restaurants", where "alias" = $1, returning *
  - [x] DOUBLE CHECK "WHERE" IS PRESENT IN SQL STRING
  - [x] Create const variable params with alias
  - [x] Handle successful calls and catch errors
- [x] Add .then method to fetch call to setState isSelected: false
- [x] Double check database for removed restaurant 
- [x] Test code in private browser
- [x] Fix all errors
- [x] Clean and remove commented code
