### ISSUE TITLE
User can see randomizer list

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#11]
## 💰 Motivation

A user should be able to see a list of saved restaurants the app will randomly choose from.

## 📐 Plan

Link app drawer option to randomizer list to allow user to see list of saved restaurants.

## 🖼️ Wireframe

<img width="509" alt="Screen Shot 2021-04-05 at 4 53 56 PM" src="https://user-images.githubusercontent.com/76749207/113640087-87bef480-962f-11eb-8c3d-7dc14f833a23.png">

<img width="576" alt="Screen Shot 2021-04-05 at 5 16 35 PM" src="https://user-images.githubusercontent.com/76749207/113641551-b2f71300-9632-11eb-8843-b04f17ca9938.png">

## ✅ Task List

- [x] Create randomize-list.jsx page
- [x] In randomize-list, import React, StarRating, and CheckIcon
- [x] Export default RandomizeList class component
- [x] In AppDrawer, add "randomize" class to check-circle icon
- [x] In App, import RandomizeList
- [x] In App handleClick method, add else if with condition for event.target.className of 'randomize'
- [x] In else if statement, change window hash to 'randomize'
- [x] Add condition to renderPage method for path = 'randomize'
- [x] Edit renderPage method in App to return <RandomizeList>
- [x] In RandomizeList, create state with restaurants property holding array of restaurants (restaurants from database)
- [x] In render method, map through restaurants and return react element for each restaurant similar to search results
  - [x] Add restaurant-randomize class to container div of each restaurant
- [x] In return of render, create 'randomize-list-container' div and 'randomize-button' in its own div element
- [x] Add return of map method as children of randomize-list-container
- [x] Create componentDidMount method to make a fetch request to database
- [x] Add response of fetch request to this.state.restaurants
- [x] Edit index.js to send GET request to randomizeList database
- [x] Make randomize-list-container overflow y
- [x] Edit 'restaurant' and 'restaurant-randomize' in css to have appropriate shadow color
- [x] Style to figma
- [x] Test in private browser
- [x] Fix all errors
- [x] Remove any commented code
