### ISSUE TITLE
User can make app randomly choose a restaurant 

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#12]
## 💰 Motivation

A user should be able to make the app randomly select a restaurant to decide where to eat.

## 📐 Plan

Add functionality to randomly select a single restaurant from the randomizer list.

## 🖼️ Wireframe

<img width="524" alt="Screen Shot 2021-04-05 at 5 00 13 PM" src="https://user-images.githubusercontent.com/76749207/113640494-68749700-9630-11eb-892e-d66cb62d53ed.png">

<img width="568" alt="Screen Shot 2021-04-05 at 5 14 58 PM" src="https://user-images.githubusercontent.com/76749207/113641448-79bea300-9632-11eb-843e-2005dbe4eba0.png">

## ✅ Task List

- [x] Change button element to anchor element in RandomizeList
- [x] Fix CSS to match figma
- [x] Have anchor element link to href="eatHere"
- [x] Create eat-here.jsx in pages directory
- [x] Import EatHere in app.jsx
- [x] Edit renderPage method in App with else if and condition of path = "eatHere"
- [x] Call EatHere component if condition is true
- [x] Create state object in EatHere with property restaurantChosen, restaurantRender, and dayOfWeek
- [x] Create componentDidMount method 
  - [x] Use "new Date()" and .getDay method and assign returned day value to variable "dayIndex"
  - [x] Call fetch request to randomizeList database
  - [x] Catch results and use Math.random() and Math.floor() to randomly pick a restaurant from results
  - [x] Send fetch request to Yelp API using business id
    - [x] Edit index.js to send new GET request to get business details using business id
    - [x] setState the return to restaurant and day variable to dayOfWeek
- [x] Console.log state to make sure functionality works
- [x] Test in private browser
- [x] Fix all errors
- [x] Remove commented code
