### ISSUE TITLE
User can see the winning/chosen restaurant 

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#13]
## 💰 Motivation

A user should be able to see details about the winning/chosen restaurant that was selected by the app.

## 📐 Plan

Create a page/module that shows the winning/chosen restaurant and details about the restaurant.

## 🖼️ Wireframe

<img width="220" alt="Screen Shot 2021-04-05 at 5 04 51 PM" src="https://user-images.githubusercontent.com/76749207/113640760-0ec09c80-9631-11eb-9bd7-d07badeb0309.png"> 
<img width="282" alt="Screen Shot 2021-04-05 at 5 14 23 PM" src="https://user-images.githubusercontent.com/76749207/113641395-63b0e280-9632-11eb-8d94-7cda817398bd.png">

## ✅ Task List

- [x] Create restaurant-hours.js
  - [x] Grab the restaurant.hours[0].open[dayOfWeek].start and  restaurant.hours[0].open[dayOfWeek].end
  - [x] Pass restaurant open and close hours and dayOfWeek from state as arguements
  - [x] Convert values to numbers, and create condition if number greater than 1200.
    - [x] If greater, (number - 1200) / 100 + 'PM'
    - [x] if equal, 1200 / 100 + PM
    - [x] if less, number / 100 + AM
  - [x] Return string value 

- [x] Create render method for EatHere
  - [x] Call RestaurantHour for hours data
  - [x] Create react element for both mobile and desktop view using state
    - [x] For mobile, create div containing div for "Eat Here", div for restaurant details, and div for "Visit Yelp" button
      - [x] Surround restaurant details inside anchor tag inside of div
      - [x] Create div for image, and bottom container
      - [x] Bottom container contains Name, Hours, Address, Rating, and Review count
      - [x] For "Visit Yelp" div, create anchor tag inside of div
    - [x] For desktop, create div containing div for "Eat Here" and restaurant details
      - [x] Create div for image and div for restaurant details
      - [x] Create elements for Name, hours, address, rating, review count, and anchor button
    - [x] In desktop, "Visit Yelp" button is inside of restaurant details div
  - [x] Return both elements and hide according to view
  - [x] Make sure anchor tags link to url and open new tab.
- [x] Style to figma
- [x] Test in private browser
- [x] Fix all errors
- [x] Remove commented code

**Comment by Samuel-Cho** [comment]
Combined issue with "User can make app randomly choose a restaurant."

**Comment by Samuel-Cho** [comment]
Re-Opened to separate choosing restaurant functionality and seeing the restaurant.
