### ISSUE TITLE
User can add a location and food type

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#2]
## 💰 Motivation

A user should be able to choose the location of where they want to eat.

## 📐 Plan

Create a field that allows the user to specify the location of where they want to eat.

## 🖼️ Wireframe

<img width="236" alt="Screen Shot 2021-04-05 at 3 48 10 PM" src="https://user-images.githubusercontent.com/76749207/113635908-58f05080-9626-11eb-8cb4-a53d96c28c34.png">

<img width="282" alt="Screen Shot 2021-04-05 at 5 28 00 PM" src="https://user-images.githubusercontent.com/76749207/113642303-5f85c480-9634-11eb-9ad5-1d25f5587784.png">

<img width="230" alt="Screen Shot 2021-04-05 at 3 54 42 PM" src="https://user-images.githubusercontent.com/76749207/113636369-41fe2e00-9627-11eb-88b0-a51c926879c4.png">

<img width="283" alt="Screen Shot 2021-04-05 at 5 27 54 PM" src="https://user-images.githubusercontent.com/76749207/113642283-4e3cb800-9634-11eb-8e10-53ccef1ecbb9.png">

## ✅ Task List

- [x] Change the button food type elements to div elements
  - [x] Create foodTypeList array of objects with properties id, position, and text
  - [x] Edit render method to map through foodTypeList array to create div elements on form 
  - [x] If id of div matches this.state.foodType, add 'selected' class for color change

- [x] Create constructor method to SearchForm component
  - [x] Create state object with location property
  - [x] Add foodType property to state object
  - [x] Bind handleChange method to 'this'
- [x] Create handleChange method in SearchForm component
  - [x] Add event listener to location input text field for handleChange method
  - [x] Get value from input element 
  - [x] Use .toLowerCase() method on value
  - [x] Add value to this.state.location property
- [x] Style form to figma
- [x] Create handleClick method to SearchForm component
  - [x] Add event listener to food type div for handleClick method
  - [x] Get id of food type div clicked and add to state object under foodType property
  - [x] Change color of selected button
  - [x] Bind handleClick method to 'this' 
- [x] Create handleSubmit method to SearchForm component
  - [x] Add event listener to form element for handleSubmit method
  - [x] Prevent default behavior of submission
  - [x] Update URL hash to include "#searchResults?location=where&foodType=food-type"
  - [x] Bind handleSubmit to 'this'
- [x] Create lib directory
  - [x] Create index.js 
  - [x] Create parse-route.js 
  - [x] Export parseRoute to index.js
  - [x] Import parseRoute from index.js in App component
- [x] Create constructor method in App component
  - [x] Create state object with route property with value using parseRoute function
- [x] Create componentDidMount method to App component
  - [x] Add event listener for hashchange
  - [x] Event listener parseRoute window.location.hash and assign to route property of state
- [x] Create renderPage method to App component
  - [x] Create condition to load Search page
  - [x] Edit render method of App to call renderPage method
- [x] Test on private browser
- [x] Fix all errors
- [x] Clean code of any comments
