### ISSUE TITLE
User can search a list of restaurant recommendations based on food type and location 

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#4]
## 💰 Motivation

A user should search for restaurant recommendations based on the location and food type the want.

## 📐 Plan

Create a list of restaurant recommendations based on the search location and food type submitted by user.

## 🖼️ Wireframe

<img width="512" alt="Screen Shot 2021-04-05 at 3 59 54 PM" src="https://user-images.githubusercontent.com/76749207/113636760-fc8e3080-9627-11eb-933a-691dd38f9a6e.png">

<img width="570" alt="Screen Shot 2021-04-05 at 5 27 04 PM" src="https://user-images.githubusercontent.com/76749207/113642218-29e0db80-9634-11eb-9970-89760ecbfd2d.png">

## ✅ Task List

- [x] Create client-error.js in server
  - [x] Create ClientError class
  - [x] Export class as default 
- [x] Create error-middleware.js in server
  - [x] Import ClientError class
  - [x] Create errorMiddleware function with appropriate conditions
  - [x] Export errorMiddleware function
- [x] Import ClientError and errorMiddleware to index.js in server
- [x] Create SearchResults component in pages directory
   - [x] Import SearchResults to app.jsx
   - [x] Edit renderPage method condition in App to call SearchResults
   - [x] Pass location and foodType from this.state.route.params as prop for SearchResults
   - [x] Add location and foodType to this.state of SearchResults
   - [x]  Send fetch request with location and food type as parameters
   - [x] Console.log response to make sure GET request is collecting data
- [x] Add app.get() request to server index.js
  - [x] Use yelp-fusion packaged to send get request to Yelp API
    - [x] Use user input for location and food type for get request
    - [x] Use .then method on response and res.json() the .jsonBody property of the response from Yelp call
- [x] Double check console to see if data is collected
- [x] Add returned data from API call to this.state.restaurants??
- [x] Test in private browser
- [x] Fix all errors
- [x] Clean up code of any comments or console.logs
