### ISSUE TITLE
User can see a list of restaurants with minor details about a restaurant

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#5]
## 💰 Motivation

A user should be able to see a list of restaurant recommendations with minor details about the restaurants.

## 📐 Plan

Create a page of restaurant recommendations showing a "check" button, picture, star rating, number of ratings, and name of each restaurant recommendation.

## 🖼️ Wireframe

<img width="522" alt="Screen Shot 2021-04-05 at 4 03 28 PM" src="https://user-images.githubusercontent.com/76749207/113637013-7b836900-9628-11eb-9e31-c48606684573.png">

<img width="420" alt="Screen Shot 2021-04-05 at 5 25 52 PM" src="https://user-images.githubusercontent.com/76749207/113642134-fe5df100-9633-11eb-9ed8-74c82be156e2.png">

## ✅ Task List

- [x] Create PageWrapper component
  - [x] Create page-wrapper.jsx in component
  - [x] Create function returning div react element 
  - [x] Based on prop passed (page hash), add class to div for background color
  - [x] Export component and import to App
  - [x]  Edit css file and add classes for PageWrapper div element
  - [x] Call PageWrapper in render method of App and pass this.state.route.path as prop
- [x] Create a div restaurant-list-container to hold restaurant recommendations 
  - [x] Map through restaurants array in state to create "restaurant" div React elements for each restaurant in render method of SearchResults
    - [x] In "restaurant" create 3 more div elements for image, details, and check icon
    - [x] Grab the restaurant name, image, rating, review count, and location (address 1?)
    - [x] Create div containers to hold each of the restaurant details
  - [x] Create star-rating.jsx component
    - [x] Loop/map through restaurants array and find rating property
    - [x] Based on rating, return a different div containing font awesome star icons
    - [x] Export StarRating component as default
    - [x] Import StarRating to search-results.jsx
  - [x] Call StarRating component with "rating" of restaurant as prop
- [x] Style to figma
  - [x] Have restaurant-list-container overflow y
  - [x] Hide address div for mobile view?
- [x] Test in private browser
- [x] Fix all errors
- [x] Clean up code of any comments or console.logs
