### ISSUE TITLE
User can visit restaurant Yelp page

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#6]
## 💰 Motivation

A user should be able to get more details about a restaurant by visiting their Yelp page.

## 📐 Plan

Add functionality to recommendation boxes leading to the specific restaurant's Yelp page.

## 🖼️ Wireframe

<img width="516" alt="Screen Shot 2021-04-05 at 4 09 43 PM" src="https://user-images.githubusercontent.com/76749207/113637404-5e9b6580-9629-11eb-8684-08f0f651e1e4.png">

<img width="574" alt="Screen Shot 2021-04-05 at 5 25 00 PM" src="https://user-images.githubusercontent.com/76749207/113642079-dec6c880-9633-11eb-928a-ba762c424df7.png">

## ✅ Task List

- [x] Mobile view
  - [x] Edit SearchResults component to grab restaurant url when mapping through restaurants from api call
  - [x] Surround restaurant div element with an anchor tag
  - [x] Clicking on restaurant will open new tab
  - [x] New tab will load restaurant url to yelp page
  - [x] Remove any default styling for anchor element
  - [x] Style div to have pointer cursor on hover
- [x] Desktop view
  - [x] Edit SearchResults component to grab restaurant url when mapping through restaurants from api call
  - [x] Surround restaurant div element with an anchor tag
  - [x] Clicking on restaurant will open new tab
  - [x] New tab will load restaurant url to yelp page
  - [x] Remove any default styling for anchor element
  - [x] Style div to have pointer cursor on hover
  - [x] Edit CSS layout for desktop view by adding one-third-column class to anchor instead of div
- [x] Edit get request api to return open restaurants only 
- [x] Test in private browser 
- [x] Fix all errors
- [x] Clean up code of any comments or console.logs
