### ISSUE TITLE
User can open and close app drawer

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#7]
## 💰 Motivation

A user should be able to navigate through the different pages in the application.

## 📐 Plan

Create an app drawer with options to specific pages of the application.

## 🖼️ Wireframe

<img width="796" alt="Screen Shot 2021-04-05 at 4 15 31 PM" src="https://user-images.githubusercontent.com/76749207/113637729-2a747480-962a-11eb-8daa-0df5f5daa626.png">

<img width="852" alt="Screen Shot 2021-04-05 at 5 24 04 PM" src="https://user-images.githubusercontent.com/76749207/113642048-c191fa00-9633-11eb-9a8e-530ea80060ff.png">

## ✅ Task List

- [x] Edit Header (or App???) component and add handleClick method bound to 'this'
- [x] Add drawerClosed property with boolean to this.state in Header or App??
- [x] In handleClick method, change boolean value of drawerClosed property 
- [x] Create app-context.js
  - [x] Use React.createContext() to make AppContext
  - [x] Export default AppContext
  - [x] Import AppContext in index.js
  - [x] Edit import in App from lib to include AppContext
- [x] Edit render method in App component and create AppContext.Provider react element with handleClick method and drawerClosed value to context
- [x] Create app-drawer component
  - [x] Import AppContext
  - [x] Grab handleClick and drawerClosed from context
  - [x] Create react element for open app drawer
     - [x] Create div for app drawer container
     - [x] Create div for menu-container
       - [x] Create header element
       - [x] Create ul element
       - [x] Create li elements with icon and page names
     - [x] Create div for transparent modal background
   - [x] Add handleClick method to li element and modal background
- [x] Import AppDrawer to App component
- [x] Call AppDrawer in render method of App component
- [x] Import AppContext in Header
  - [x] Grab handleClick from context in render method
  - [x] Add handleClick method to app drawer icon
- [x] Style app drawer to figma for mobile
- [x] Style app drawer to figma for desktop
- [x] Test in private browser
- [x] Fix all errors
- [x] Clean and remove commented code
