### ISSUE TITLE
User can update location and food type

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#8]
## 💰 Motivation

A user should be able change the location and food type they want to eat.

## 📐 Plan

Link app drawer option to search page to allow user to do a new search based on changes to location and food type.

## 🖼️ Wireframe

<img width="786" alt="Screen Shot 2021-04-05 at 4 18 54 PM" src="https://user-images.githubusercontent.com/76749207/113637962-a40c6280-962a-11eb-9be0-97e9f50e91bc.png">

<img width="851" alt="Screen Shot 2021-04-05 at 5 23 16 PM" src="https://user-images.githubusercontent.com/76749207/113642011-a32bfe80-9633-11eb-967c-ea0dc01c66d0.png">

## ✅ Task List

- [x] Edit renderPage method in App to return Home if path is 'search'
- [x] Edit PageWrapper condition to include 'search' path
  - [x] If path is 'search', background is white
- [x] Edit li elements in AppDrawer component
  - [x] Add className 'search' to Search Restaurant icon and text
  - [x] Add className 'searchResults' to Restaurant List icon and text
- [x] Edit handleClick method in App component
  - [x] Add event to method parameter 
  - [x] Add condition to grab className of li element (event.target.className)
  - [x] If className matches condition, change window hash to className of li element
- [x] Going back to restaurant list should save previous search???
  - [x] Pass route params location and foodType as props for AppDrawer??
  - [x] Add state object to AppDrawer with property previousSearchParams object with properties foodType and location assigned to null.
  - [x] Add componentDidUpdate method to AppDrawer
  - [x] Grab params from context.route
  - [x] Grab foodType and location from params
  - [x] Create condition comparing location to this.state.location and null
  - [x] Update state with foodType and location if condition true
  - [x] Surround li content for Restaurant List with anchor tag
  - [x] Build href from state property in anchor tag
  - [x] Fix CSS for anchor tag in AppDrawer restaurant list
- [x] Test in private browser
- [x] Fix all errors
- [x] Remove and clean any commented code
