### ISSUE TITLE
User can add restaurant to the randomizer list 

### ISSUE THREAD

**Issue by Samuel-Cho** [Samuel-Cho/teeter-taste#9]
## 💰 Motivation

A user should be able to add a restaurant to a list for the app to randomly select where to eat.

## 📐 Plan

Add functionality to check button to save specific restaurant to the randomizer list.

## 🖼️ Wireframe

<img width="510" alt="Screen Shot 2021-04-05 at 4 42 36 PM" src="https://user-images.githubusercontent.com/76749207/113639406-f4d18a80-962d-11eb-9a3f-31a1bf26678c.png">

<img width="572" alt="Screen Shot 2021-04-05 at 5 22 32 PM" src="https://user-images.githubusercontent.com/76749207/113641957-868fc680-9633-11eb-9e7a-3197f3c3bd86.png">

## ✅ Task List

- [x] Setup database randomizerList
  - [x] Edit schema.sql to create "restaurants" table
  - [x] Add columns: restaurantId, alias, url, imageUrl, name, address1, rating, reviewCount
  - [x] Make restaurantId primary key
  - [x] Edit data.sql to insert example restaurant into database???
- [x] Run postgresql
- [x] Create database randomizerList: createdb randomizerList
- [x] Import database schema and test data: npm run db:import
- [x] Run pgweb --db=randomizerList
- [x] Visit http://localhost:8081 to see database in web browser.
- [x] Change anchor tag in render method to surround elements except div with icon
- [x] Fix css for mobile and desktop layout
- [x] Create function CheckIcon
  - [x] Create restaurantsDbAliases property in state
  - [x] Create handleClick method in SearchResults
    - [x] Add handleClick and event listener to icon element
    - [x] handleClick change icon class name to appropriate icon
    - [x] Create condition based on target's current class and change class
  - [x] Create fetch request to get restaurants in database and add to restaurantsDbAliases
  - [x] Edit index.js to send get request to database and return all restaurant data
  - [x] Pass this.state.retaurantsDbAliases and restaurant as arguments
  - [x] Add prop arguments into state 
  - [x] Filter through db restaurants and check to see if alias matches
  - [x] If no match, return unchecked icon, if match, return checked icon
- [x] Edit handleClick method to send fetch request based on condition of event.target.className
  - [x] Create const variable req object with method, headers, and body properties
  - [x] Edit index.js and create post request to database to add restaurant information
